name: appmovies
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0  
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  social_auth_buttons: ^2.0.2



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^6.2.1
  

  
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/